#!/usr/bin/env python3

from os import write
import subprocess
import sys
import re
import urllib.request

def write_to_clipboard(output):
    process = subprocess.Popen(
        'pbcopy', env={'LANG': 'en_US.UTF-8'}, stdin=subprocess.PIPE)
    process.communicate(output.encode('utf-8'))

url = sys.argv[1]
url = url.replace('%2F', '/')
m = re.search(r"arxiv.org/(pdf|abs)/\d+\.\d+", url)
url = m.group(0).replace('/pdf/', '/abs/')

req = urllib.request.urlopen('https://' + url)
body = req.read().decode('utf-8')

m = re.search(r"<meta name=\"citation_author\" content=\"(.+),", body)
last_name = m.group(1)

year = '20'+url[14:16]
link = f"[{last_name} et al., {year}]({'https://'+url})"
write_to_clipboard(link)
print(link)
