#!/usr/bin/env python

import json
import sys


def main():
    for line in sys.stdin:
        data = {}
        for field in line.split('\t'):
            data.update(json.loads(field))

        print(json.dumps(data, ensure_ascii=False))


if __name__ == '__main__':
    main()
